  matrix:
    include:
      - language: python
        python: "3.5"
        before_script:
          - pip install tox
        env:
        - INFO=PythonTests
        script:
        - tox -e py35
        - tox -e coverage
      - language: python
        python: "3.6"
        before_script:
          - pip install tox
        env:
        - INFO=PythonTests
        script:
        - tox -e py36

      - language: python
        python: "3.5"
        env:
          - INFO=PythonCodeCheck
        before_script: make pydevrequirements
        script:
          - make flake8
          - make pydocstyle

      - language: node_js
        env:
          - INFO=JavaScriptTest
        node_js: "7"
        script:
          - make qunit

      - language: node_js
        env:
          - INFO=JavaScriptCodeCheck
        node_js: "7"
        script:
          - make eslint


  git:
    depth: 3
  cache:
    - pip
    - directories:
      - node_modules # NPM packages

  # safelist
  branches:
    only:
    - master
    - develop

  #after_success:
  # not necessary, done by tox
  #  coveralls
